### ISSUE TITLE
omz zarr logging

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#383]
@KateMoreva 

In the current master there is still quite some logging happening:

```
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
dataBlockIndices[0, 0]
Path0.0
readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/marker_tophat_WellE06_0008.ome.zarr/s3/0.0
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
dataBlockIndices[0, 0]
Path0.0
readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/marker_tophat_WellE07_0007.ome.zarr/s3/0.0
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
dataBlockIndices[0, 0]
Path0.0
```

Could you disable this?

**Comment by KateMoreva** [comment]
Solved in https://github.com/mobie/mobie-viewer-fiji/pull/386

**Comment by tischi** [comment]
@KateMoreva Has this been merged into master?
I am still seeing:
```
Path0.0
readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/nuclei_WellE07_0007.ome.zarr/s3/0.0
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
dataBlockIndices[0, 0]
Path0.0
readBlock path: /g/kreshuk/pape/Work/mobie/covid-if-project/data/20200406_164555_328/images/ome-zarr/nuclei_WellE06_0008.ome.zarr/s3/0.0
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
[shape, chunks, fill_value, dtype, filters, compressor, order, zarr_format]
dataBlockIndices[0, 0]
```
