### ISSUE TITLE
Projects made with the project creator can no longer be opened

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#513]
On the current mobie-beta, making a simple project with the project creator i.e.
- Make a dataset called 'test'
- Add an image (e.g. the sample 'MRI Stack' image in fiji)
- Open it in MoBIE

Gives the following error:
```
Fetched 0 image source(s) in 5 ms, using 11 thread(s).Exception in thread "pool-7-thread-1" 
java.lang.NullPointerException
	at org.embl.mobie.io.n5.loaders.N5ImageLoader.getSequenceDescription(N5ImageLoader.java:173)
	at org.embl.mobie.io.n5.openers.N5Opener.readFile(N5Opener.java:30)
	at org.embl.mobie.io.n5.openers.N5Opener.openFile(N5Opener.java:22)
	at org.embl.mobie.viewer.source.SpimDataOpener.openBDV(SpimDataOpener.java:92)
	at org.embl.mobie.viewer.source.SpimDataOpener.openSpimData(SpimDataOpener.java:65)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:298)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-25" java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.adaptConverter(ImageSliceView.java:92)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.show(ImageSliceView.java:62)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.<init>(ImageSliceView.java:47)
	at org.embl.mobie.viewer.view.ViewManager.showImageDisplay(ViewManager.java:367)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:334)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:289)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:215)
	at org.embl.mobie.viewer.MoBIE.openDataset(MoBIE.java:149)
	at org.embl.mobie.viewer.MoBIE.<init>(MoBIE.java:85)
	at org.embl.mobie.viewer.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:25)
	at org.embl.mobie.viewer.projectcreator.ui.ProjectsCreatorPanel.lambda$null$8(ProjectsCreatorPanel.java:264)
at java.lang.Thread.run(Thread.java:748)
```

The n5 image created opens fine with normal bigdataviewer, so it's something to do with how MoBIE is reading it.

**Comment by K-Meech** [comment]
@tischi @KateMoreva Any ideas for this one? I think it's something to do with the recent changes for image loading.

**Comment by martinschorb** [comment]
Also happens when loading an "old" spec-v2 dataset from disk.

**Comment by martinschorb** [comment]
From S3 it loads fine (it just feels a little slow...).

**Comment by constantinpape** [comment]
> Also happens when loading an "old" spec-v2 dataset from disk.

What do you mean by "old"? One that was created with the project creator earlier?
Could you maybe share the location for one of these datasets on a group share? That would help to debug the issue.

**Comment by martinschorb** [comment]
> One that was created with the project creator earlier?

No that's the centriole tomo dataset that I created using Python:

It's in 

```
/g/schwab/Tobias/MoBIE
```

**Comment by K-Meech** [comment]
It might be a general issue with opening any mobie project from the file system then (rather than just project creator)

**Comment by constantinpape** [comment]
Indeed, this seems to be an issue with opening projects from the file system, it also fails for the platybrowser (`/g/arendt/EM_6dpf_segmentation/platy-browser-data`) which can be opened via s3.

**Comment by KateMoreva** [comment]
> @tischi @KateMoreva Есть идеи по этому поводу ? Я думаю, это как-то связано с недавними изменениями загрузки изображений.

I'll try to investigate this, but I implemented new functionality with minimal changes to the old one (use new constructors and methods).

**Comment by constantinpape** [comment]
@tischi @KateMoreva 
Just fyi: opening a project with bdv.n5 from the filesystem still fails for the newest MoBIE-beta (e.g. `/g/kreshuk/pape/Work/mobie/arabidopsis-root-lm-datasets`). Opening a project with ome.zarr from the filesystem however works (`/g/kreshuk/pape/Work/mobie/covid-if-project`).

**Comment by martinschorb** [comment]
Then we just use OME-Zarr for every project from now on... 😄

**Comment by KateMoreva** [comment]
> @tischi @KateMoreva Just fyi: opening a project with bdv.n5 from the filesystem still fails for the newest MoBIE-beta (e.g. `/g/kreshuk/pape/Work/mobie/arabidopsis-root-lm-datasets`). Opening a project with ome.zarr from the filesystem however works (`/g/kreshuk/pape/Work/mobie/covid-if-project`).

I'll investigate this problem.

**Comment by constantinpape** [comment]
@KateMoreva any progress here? Let us know if we can help somehow.
(It would be good to fix this issue soon, because as far as I can see this is the only one blocking us from making the main release)

**Comment by KateMoreva** [comment]
> @KateMoreva any progress here? Let us know if we can help somehow. (It would be good to fix this issue soon, because as far as I can see this is the only one blocking us from making the main release)

@constantinpape 
Fixed in develop.

**Comment by constantinpape** [comment]
Thanks @KateMoreva!

@tischi let me know when you have deployed this to MoBIE-beta, then I can check if the issue is also fixed there.

**Comment by tischi** [comment]
@constantinpape 

Done:
```
[INFO] Successfully uploaded to jars/mobie-viewer-fiji-2.0.4.jar-20211111082540
[INFO] Successfully uploaded to jars/mobie-io-1.0.7.jar-20211111082540
```

**Comment by constantinpape** [comment]
It seems to work in general, but there are still some issues for certain projects (I made specific issues about this):
- Loading platybrowser due to non-standard data path in xml #526 
- Scrolling across time #527

**Comment by KateMoreva** [comment]
@constantinpape 
@tischi 
I am really sorry for this mistake.
There is a new **mobie-viewer-fiji 2.0.5**, where this should work.

**Comment by constantinpape** [comment]
Everything is working for me now. @K-Meech @martinschorb could you please check if your projects can be opened as well now?

**Comment by K-Meech** [comment]
Yes - I can open projectcreator projects again now. Thanks @KateMoreva!

**Comment by martinschorb** [comment]
Seems to work nicely.

Thanks!
